spring.application.name=gerenciador-pedidos

#Conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://${DB_HOST}/gerenciador_pedidos
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ao executar a aplicação, a JPA verifica se mudou algo nas classes e faz o update no banco de dados
# create-drop (apaga ao desligar a aplicação)
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console
spring.jpa.show-sql=true



